# Generated by Django 3.2.2 on 2024-03-19 22:11

import chat_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default/default.jpg', null=True, upload_to=chat_app.models.uploadImagePath),
        ),
    ]
